# Generated by Django 3.1.6 on 2021-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uesr_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('coupon_id', models.CharField(max_length=200)),
            ],
        ),
    ]
