# Generated by Django 3.1.6 on 2021-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='uesr_id',
            new_name='user_id',
        ),
    ]
