# Generated by Django 3.1.3 on 2021-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stream_url', models.URLField(null=True)),
                ('vod_url', models.URLField(null=True)),
                ('stream_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=500)),
                ('influencer_name', models.CharField(max_length=200)),
                ('influencer_id', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('thumbnail_url', models.URLField(null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyVod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('vod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediastream')),
            ],
        ),
    ]
