# Generated by Django 3.1.6 on 2021-03-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStream',
            fields=[
                ('mux_livestream_playback_id', models.URLField(null=True)),
                ('mux_livestream_id', models.CharField(max_length=200)),
                ('mux_asset_id', models.CharField(max_length=200, null=True)),
                ('mux_asset_playback_id', models.URLField(null=True)),
                ('vod_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('notice', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('influencer_name', models.CharField(max_length=200)),
                ('influencer_id', models.CharField(max_length=200)),
                ('influencer_thunmbnail', models.URLField(null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(default='0원', max_length=200)),
                ('product_sale', models.CharField(default='0', max_length=200)),
                ('product_brand', models.CharField(max_length=200, null=True)),
                ('product_thumbnail', models.URLField(null=True)),
                ('product_list', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('vod_view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('vod_id', 'influencer_id')},
            },
        ),
    ]
