# Generated by Django 3.1.6 on 2021-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastream',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediastream',
            name='product_sale',
            field=models.IntegerField(default=0),
        ),
    ]
