# Generated by Django 3.1.3 on 2021-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastream',
            name='vod_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
