# Generated by Django 3.1.3 on 2021-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210308_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastream',
            name='product_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
