# Generated by Django 3.1.3 on 2021-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediastream_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastream',
            name='push_count',
            field=models.IntegerField(default=0),
        ),
    ]
