version: '3.7'

services:
  web:
    build: ./app
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 asgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev

