version: '3'
# ARG django_port = 8000
# ARG daphne_port = 9000
services:
  nginx:
    build: ./nginx
    image: "nginx:latest"
    container_name: "nginx-server"
    volumes:
      - ./app/static/:/static/
    ports:
      - "80:80"
    depends_on:
      - daphne
      - django
  redis:
    image: redis:latest
    container_name: "redis-server"
    ports:
      - "6379:6379"
  django: &django
    build: ./app
    container_name: "django-server"
    command: bash -c "gunicorn -w 1 -k gevent -b 0.0.0.0:8000 loha.wsgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    expose:
      - "8000"
  daphne:
    <<: *django
    container_name: "chat-server"
    command: bash -c "daphne -b 0.0.0.0 -p 8001 dj_chat.asgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8001:8001"
    expose:
      - "8001"
    depends_on:
      - redis
    links:
      - redis


