version: '3'
# ARG django_port = 8000
# ARG daphne_port = 9000
services:
  nginx:
    build: ./nginx
    container_name: "nginx-server"
    volumes:
      - ./app/static/:/home/ubuntu/static/
    ports:
      - "80:80"
    depends_on:
      - daphne
      - django
  redis:
    image: redis:latest
    restart: always
  django: &django
    build: ./app
    container_name: "django-server"
    command: bash -c "gunicorn -b 0.0.0.0:8000 loha.wsgi:application"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - "8000"
  daphne:
    <<: *django
    container_name: "chat-server"
    command: bash -c "daphne -b 0.0.0.0 -p 8001 loha.asgi:application"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - "8001"



