version: '3'
# ARG django_port = 8000
# ARG daphne_port = 9000
services:
  nginx:
    build: ./nginx
    image: "nginx:latest"
    container_name: "nginx-server"
    volumes:
      - ./app/static/:/static/
      - ./config/:/etc/nignx.conf.d
    networks:
      - front
      - back
    ports:
      - "80:80"
    depends_on:
      - daphne
      - django
    links:
      - django
      - daphne
  redis:
    image: redis:latest
    container_name: "redis-server"
    networks:
      - back
    ports:
      - "6379:6379"
  django: &django
    build: ./app
    container_name: "django-server"
    command: bash -c
      "python manage.py migrate
      &&python manage.py collectstatic --noinput
      && gunicorn -b 0.0.0.0 -p 7000 loha.wsgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "7000:7000"
    expose:
      - "7000"
    links:
      - nginx
    networks:
      - front
      - back
  daphne:
    <<: *django
    container_name: "chat-server"
    command: bash -c
      "daphne -b 0.0.0.0 -p 9000 loha.asgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
      - nginx

networks:
  front:
  back:

