version: '3.7'

ARG django_port = 8000
ARG daphne_port = 9000

services:
  nginx:
    build: ./nginx
    image: "nginx:latest"
    container_name: "nginx-server"
    volumes:
      - ./app/static/:/static/
    networks:
      - front
      - back
    ports:
      - "80:80"
    depends_on:
      - daphne
      - django
    links:
      - django
      - daphne
  redis:
    image: redis:latest
    container_name: "redis-server"
    networks:
      - back
    ports:
      - "6379:6379"
  django: &django
    build: ./app
    container_name: "django-server"
    command: bash -c
      "python manage.py migrate
      &&python manage.py collectstatic --noinput
      && gunicorn -b 0.0.0.0 -p ${django_port} loha.wsgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "${django_port}:${django_port}"
    networks:
      - front
      - back
  daphne:
    <<: *django
    container_name: "chat-server"
    command: bash -c
      "daphne -b 0.0.0.0 -p ${daphne_port} loha.asgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "${daphne_port}:${daphne_port}"
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis

networks:
  front:
  back:

