version: '3.7'

services:
  web:
    build: ./app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev

