version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 loha.wsgi:application
    #command: gunicorn loha.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env.prod
