version: '3.7'

services:
  nginx:
    build: ./nginx
    image: "nginx:latest"
    volumes:
      - ./app/static/:/static/
    networks:
      - front
      - back
    ports:
      - "80:80"
    depends_on:
      - daphne
      - django
    links:
      - daphne
  redis:
    image: redis:alpine
    networks:
      - back
    ports:
      - "6379:6379"
  daphne:
    build: ./app
    container_name: "chat-server"
    command: bash -c
      "daphne -b 0.0.0.0 -p 8001 loha.asgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8001:8001"
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
  django:
    build: ./app
    container_name: "gunicorn-django"
    command: bash -c
      "python manage.py migrate
      &&python manage.py collectstatic --noinput
      && gunicorn -b 0.0.0.0 -p 8000 loha.wsgi:application"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - front
      - back

networks:
  front:
  back:

