# Generated by Django 2.2.16 on 2020-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('client_id', models.TextField(default='ehSKOHqFTiAKp4coWMTCaH')),
                ('client_secret', models.TextField(default='T7fVHR5KEaOfu6IKXhszFM')),
                ('access_token', models.TextField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('refresh_token_expires_at', models.DateTimeField(null=True)),
                ('redirect_url', models.URLField(null=True)),
            ],
        ),
    ]
