# Generated by Django 3.1.6 on 2021-03-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livealarm',
            old_name='Live_id',
            new_name='vod_id',
        ),
    ]
