# Generated by Django 3.1.3 on 2021-03-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livealarm',
            old_name='Live_id',
            new_name='vod_id',
        ),
    ]
